### ISSUE TITLE
overwrite.yaml not overwriting configuration

### ISSUE THREAD

**Issue by KaelBaldwin** [covexo/devspace#314]
Probably I'm just making a mistake with my overwrite.yaml file somewhere, but I'm not seeing it.

I'm using Kaniko as the build engine. I'm overwriting my registry auth credentials, but it doesn't seem to be working. The image name I've overwritten isn't working either.

I even cloned the repo and attempted to debug this a bit (on master branch) and found something strange happening.

In `pkg/devspace/config/configutil/get.go` I dumped the config object in several places.

After line 84, when "overwriteConfigRaw" is first created. The content of that object was indeed my overwrite.yaml

But when I check the config object after the merge on line 88 (merging config and overwriteConfig) I see that the config object was not changed at all.

To help, here is my config file and overwrite file, with some adjustments to make it a little more generic.

at `./.devspace/config.yaml`
```
cluster:
  kubeContext: develop
  namespace: devspace
devSpace:
  deployments:
  - helm:
      chartPath: ./chart
    name: devspace-app
  ports:
  - labelSelector:
      release: devspace
    portMappings:
    - localPort: 80
      remotePort: 7001
  sync:
  - containerPath: /app
    labelSelector:
      release: devspace-app
    localSubPath: ./
    uploadExcludePaths:
    - Dockerfile
    - .devspace/
    - chart/
    - vendor/
    - node_modules/
    - web/uploads/
images:
  default:
    name: devspace/app
    registry: custom
    build:
      kaniko:
        namespace: devspace
        cache: true
registries:
  custom:
    url: custom.registry.com
    auth:
      username: overwritethis
      password: andthis
version: v1alpha1
```

contents of `./.devspace/overwrite.yaml`
```
cluster:
  namespace: different-namespace
images:
  default:
    name: devspace/another-name
registries:
  custom:
    auth:
      username: RealUserName
      password: realpass
```

**Comment by KaelBaldwin** [comment]
I'm seeing the same thing on windows and linux. I'm switching back to 2.0.1 and seeing if that works though.

**Comment by KaelBaldwin** [comment]
There's a good chance I'm just making a mistake with my overwrite.yaml somehow, but I'm not seeing it.

**Comment by LukasGentele** [comment]
Hi @KaelBaldwin! Thank you for the detailed info and even for trying to debug the issue. I will take a deeper tomorrow. There might be a bug within the config merge algorithm. I will let you know as soon as there is a new release with a fix.

**Comment by KaelBaldwin** [comment]
thanks!

**Comment by LukasGentele** [comment]
@KaelBaldwin: I pushed a fix #319 - does it work for you using the branch issue-314?

**Comment by KaelBaldwin** [comment]
checking, thanks

**Comment by KaelBaldwin** [comment]
```
goroutine 1 [running, locked to thread]:
reflect.Value.IsNil(...)
        C:/Go/src/reflect/value.go:1018
github.com/covexo/devspace/pkg/devspace/config/configutil.merge(0x17399c0, 0xc0006e8c00, 0x17399c0, 0xc0006e8d80, 0xc0006e8c00, 0xc0006e8d80)
        C:/Users/kabaldwin/projects/devspace/pkg/devspace/config/configutil/merge.go:36 +0x149b
github.com/covexo/devspace/pkg/devspace/config/configutil.Merge(0x17399c0, 0xc0006e8c00, 0x17399c0, 0xc0006e8d80)
        C:/Users/kabaldwin/projects/devspace/pkg/devspace/config/configutil/merge.go:19 +0x64
github.com/covexo/devspace/cmd.(*InitCmd).Run(0xc0003f5e30, 0x0, 0xc0006cbc40, 0x0, 0x0)
        C:/Users/kabaldwin/projects/devspace/cmd/init.go:137 +0x772
github.com/covexo/devspace/cmd.(*UpCmd).Run(0xc0001fa770, 0xc000893180, 0x3146df8, 0x0, 0x0)
        C:/Users/kabaldwin/projects/devspace/cmd/up.go:121 +0x335
github.com/covexo/devspace/cmd.(*UpCmd).Run-fm(0xc000893180, 0x3146df8, 0x0, 0x0)
        C:/Users/kabaldwin/projects/devspace/cmd/up.go:92 +0x59
github.com/spf13/cobra.(*Command).execute(0xc000893180, 0x3146df8, 0x0, 0x0, 0xc000893180, 0x3146df8)
        C:/Users/kabaldwin/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0x310b3a0, 0x40b0000, 0x0, 0x17b8160)
        C:/Users/kabaldwin/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0x310b3a0, 0xc0006cbf30, 0x40c4ff)
        C:/Users/kabaldwin/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x32
github.com/covexo/devspace/cmd.Execute()
        C:/Users/kabaldwin/projects/devspace/cmd/root.go:39 +0x90
main.main()
        C:/Users/kabaldwin/projects/devspace/main.go:16 +0x45
```

investigating a bit on my end as well now

**Comment by KaelBaldwin** [comment]
@LukasGentele the images.default.name still does not seem to get overwritten (what I'm mainly looking to change and the easiest to see), I tried it on both windows and linux.

I continue to get the [INFO]   Building image 'devspace/iaapps' with engine 'kaniko'
(I'm looking for it to change from "devspace/iaapps" to "devspace/iaapps-kael")

**Comment by KaelBaldwin** [comment]
I'm going to try resetting the configuration in the project and rebuilding it from scratch just to be sure I haven't messed something up.

**Comment by LukasGentele** [comment]
@KaelBaldwin: So, I just pushed another fix (see PR #320). Does the branch "issue-315" work for you?

**Comment by KaelBaldwin** [comment]
checking...

**Comment by LukasGentele** [comment]
sorry, did not check `devspace init` which you reported, too. Let me fix that first

**Comment by KaelBaldwin** [comment]
no problem

**Comment by LukasGentele** [comment]
Alright, now you're good to go. Branch "issue-315" should work. Let me know if it works for you, too.

**Comment by KaelBaldwin** [comment]
ok, I'll let you know asap, thanks!

**Comment by KaelBaldwin** [comment]
Woohoo! That did it, you're awesome! Thanks!

**Comment by LukasGentele** [comment]
Perfect, thank you! I will merge it into master, so the fix can be shipped with the next release planned for tomorrow. Thanks for reporting.
